accelerator: null
accumulate_grad_batches: 1
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
automatic_optimization: null
batch_size: 32
benchmark: false
causal: true
channel_growth: 1
channel_width: 32
check_val_every_n_epoch: 1
checkpoint_callback: true
default_root_dir: lightning_logs/bulk/9-uTCN-300__causal__4-10-13__fraction-0.1-bs32
deterministic: false
dilation_growth: 10
distributed_backend: null
enable_pl_optimizer: true
eval_length: 131072
fast_dev_run: false
flush_logs_every_n_steps: 100
gpus: 1
gradient_clip_val: 0
grouped: false
kernel_size: 13
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
lr: 0.0003
max_epochs: 60
max_steps: null
min_epochs: 1
min_steps: null
model_type: tcn
move_metrics_to_cpu: false
nblocks: 4
ninputs: 1
noutputs: 1
nparams: 2
num_examples: 4
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
num_workers: 16
overfit_batches: 0.0
plugins: null
precision: 16
preload: true
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: 1
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
root_dir: /import/c4dm-datasets/SignalTrain_LA2A_Dataset_1.1
sample_rate: 44100
save_dir: null
shuffle: true
skip_connections: false
stack_size: 10
sync_batchnorm: false
terminate_on_nan: false
tpu_cores: !!python/name:pytorch_lightning.utilities.argparse_utils._gpus_arg_default ''
track_grad_norm: -1
train_fraction: 1.0
train_length: 65536
train_loss: l1+stft
train_subset: train
truncated_bptt_steps: null
val_check_interval: 1.0
val_subset: val
weights_save_path: null
weights_summary: top
